### ISSUE TITLE
New maintainers

### ISSUE THREAD

**Issue by jrbourbeau** [pycondor/pycondor#146]
Hi All,

Over the past two and a half years I've been at organizations where I no longer have access to an HTCondor cluster and haven't had much bandwidth to continue development / maintenance on `pycondor`. That said, there are still people opening issues / pull requests and I would hate to be a bottleneck in letting `pycondor` progress. Are there folks that are interested in helping maintain this project?

cc @jodergrosse @duncanmmacleod @mmatera who may be interested (though there's certainly no obligation here)

**Comment by jodergrosse** [comment]
Hi @jrbourbeau,

Thanks for all you've done already! I can contribute a bit of time and work!

**Comment by GregoryAshton** [comment]
@jrbourbeau I'm the maintainer of a project which depends on pycondor. Firstly, let me say thank you for writing it in the first place, it made my life quite a bit easier during the development. 

It has recently been raised that `pycondor` v0.5.0 (the current pypi release) is incompatible with python 3.10. This makes our package incompatible with python 3.10. 

To this end, I'd be happy to take on maintenance of `pycondor` to help get new releases out with bug fixes.

**Comment by jrbourbeau** [comment]
Apologies for the delayed response -- I've been away from the keyword on leave the past several weeks. Thanks @jodergrosse @GregoryAshton, I've invited you both to be collaborators to this repository. Please let me know if you have any questions or if there are additional resources you need access to (e.g. PyPI)

**Comment by jodergrosse** [comment]
No worries. I guess we all got things to do :)
I'll make myself familiar with everything. Will come back to you as soon as questions arise!

@GregoryAshton lets coordinate for some merges and a new version!

**Comment by GregoryAshton** [comment]
That sounds good @jodergrosse. I'll do the same. It may be useful to meet (virtually) to chat about a broad-scale plan.

**Comment by jrbourbeau** [comment]
> should this project be moved into a neutral namespace?

Happy to do so. I just created a `pycondor` org on GitHub and invited @jodergrosse @GregoryAshton and @duncanmmacleod. I've held off on actually transferring this repo to the org as I anticipate there will be some corresponding updates that need to be made (i.e. several `jrbourbeau` --> `pycondor` updates). I wanted to make sure folks have bandwidth for those updates before doing the repo transfer

**Comment by GregoryAshton** [comment]
Hi @jrbourbeau thanks for creating the org. A new release has not happened yet, I do have time over the next weeks to devote to this.

**Comment by jrbourbeau** [comment]
@GregoryAshton if you're up for making the relevant changes needed as part of migrating to a separate `pycondor` GitHub, that would be very welcome. Let me know when a good time would be to transfer the repo over

**Comment by GregoryAshton** [comment]
@jrbourbeau would you prefer I make the changes before we migrate, or after? I would think we should migrate then fix it. In which case, please do transfer the repo and then I'll get started.

**Comment by jrbourbeau** [comment]
Thanks @GregoryAshton -- transferred over to `pycondor/pycondor`

**Comment by GregoryAshton** [comment]
Hi @jrbourbeau, I don't think @jodergrosse and I yet have full access to the repository. While I can see myself  as a member of "pycondor" (https://github.com/orgs/pycondor/people), I can't push to the actual repo or see any settings. Perhaps you also have to add us to the repository itself ?

**Comment by duncanmmacleod** [comment]
@jrbourbeau, can you create a `pycondor/dev` (or similar) 'team'  as part of the org with admin rights for the pycondor repo?

**Comment by GregoryAshton** [comment]
Closing this as the new maintainers are in place!
