### ISSUE TITLE
Migrate documentation to readthedocs.io

### ISSUE THREAD

**Issue by duncanmmacleod** [pycondor/pycondor#150]
Currently the documentation is hosted using GitHub Pages, which requires a GitHub Actions workflow to build it. I would like to recommend migrating the documentation to https://readthedocs.org, which can integrate with pull requests and then automatically build 'latest' (default branch) and 'stable' (tags) versions and host all of them concurrently.

**Comment by GregoryAshton** [comment]
This looks like a good idea. It may also be worth adding a redirect from the old pages if possible.

**Comment by duncanmmacleod** [comment]
This was configured in 0d4c29770ac7b94104e6e4e21bd210f929de3592.
