### ISSUE TITLE
Enable integrations for CodeCov and ReadTheDocs

### ISSUE THREAD

**Issue by duncanmmacleod** [pycondor/pycondor#153]
@jrbourbeau, I have tried to set up integrations for CodeCov and ReadTheDocs, I believe that they are waiting on your approval at the organisation level. Can you please review and approve these as appropriate, possibly from https://github.com/organizations/pycondor/settings/installations?

**Comment by jrbourbeau** [comment]
Sorry for the delay @duncanmmacleod -- I'm just getting back from a couple weeks of PTO. I've approved the codecov and readthedocs integration requests. Please let me know if there's anything else needed for this at the moment
